//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRCoderArt.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QRCoderArt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Demo project WinForm application
        ///creating a file with a picture of a QR code based on QRCoder (1.4.1).
        ///  - the ability to create a label (top layer)
        ///  - or a background image (background) based on ArtQRCode.cs.
        ///
        ///using
        ///   1. Select payload
        ///   2. Select construction
        ///   3. Fill in the parameters
        ///
        ///Payload interface - dynamic (Reflection) QRCoder.dll
        ///
        ///QR code picture generator QRCoder 1.4.1 QRCoder.dll + QRCoderDemo
        ///(Raffael Herrmann)
        ///https://github.com/codebude/QRCoder
        ///
        ///ArtQRCode.cs file backgro [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string AboutString {
            get {
                return ResourceManager.GetString("AboutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на |	&lt;/body&gt;
        ///			|&lt;/html&gt;.
        /// </summary>
        internal static string ErrorHTMLFooter {
            get {
                return ResourceManager.GetString("ErrorHTMLFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///			|	&lt;head&gt; 
        ///			|		&lt;meta charset=&apos;utf-8&apos;&gt;
        ///			|		&lt;title&gt;Гороскоп Виджет&lt;/title&gt;
        ///			|		&lt;style type=&apos;text/css&apos;&gt;
        ///			|			body {
        ///			|				font-family:&apos;Times New Roman&apos;, &apos;Sans-Serif&apos;, &apos;Lucida Sans Unicode&apos;, &apos;Lucida Grande&apos;;;
        ///			|				font-weight: normal;
        ///			|			}
        ///			|			table {
        ///			|				font-size: 14px;
        ///			|  				background: white;
        ///			|				width: 100%;
        ///			|				border-collapse: collapse;
        ///			|				}
        ///			|			td.first {
        ///			|				width: 80px;
        ///			|				}
        ///			|			td.last {
        ///			|				text-align: right;
        ///		 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ErrorHTMLHeader {
            get {
                return ResourceManager.GetString("ErrorHTMLHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;table&gt;  
        ///			|		&lt;tr&gt;.
        /// </summary>
        internal static string ErrorHTMLTableBegin {
            get {
                return ResourceManager.GetString("ErrorHTMLTableBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;/tr&gt;
        ///			|	&lt;/table&gt;.
        /// </summary>
        internal static string ErrorHTMLTableEnd {
            get {
                return ResourceManager.GetString("ErrorHTMLTableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string ErrorHTMLTableRow {
            get {
                return ResourceManager.GetString("ErrorHTMLTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon qr {
            get {
                object obj = ResourceManager.GetObject("qr", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap qr1 {
            get {
                object obj = ResourceManager.GetObject("qr1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon ric_ {
            get {
                object obj = ResourceManager.GetObject("ric_", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smart {
            get {
                object obj = ResourceManager.GetObject("smart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
